FROM golang:1.15.7-alpine3.13 AS builder
WORKDIR /go/src/github.com/alvarotor/deletemenow/
COPY go.* *.go ./
ARG tag
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-X main.version=$tag" -o /dist/app .

FROM alpine:3.13.1
COPY --from=builder /dist/app .
EXPOSE 3001
CMD ["./app"]