version: "3.9"
services:
  app:
    container_name: go-delve-docker-vscode-example
    build:
      context: .
      dockerfile: ./Dockerfile.debug
    restart: unless-stopped
    security_opt:
      - "seccomp:unconfined"
    tty: true
    stdin_open: true
    ports:
      - 80:3001
      - 2345:2345
